export const INVOICE_CREATE = "INVOICE_CREATE";
export const INVOICE_GET_ALL = "INVOICE_GET_ALL";
export const INVOICE_GET_BY_ID = "INVOICE_GET_BY_ID";
export const INVOICE_UPDATE = "INVOICE_UPDATE";
export const INVOICE_DELETE = "INVOICE_DELETE";
export const INVOICE_ERROR = "INVOICE_ERROR";