export const CREATE_LEADS_LOADING = "CREATE_LEADS_LOADING";
export const CREATE_LEADS_SUCCESS = "CREATE_LEADS_SUCCESS";
export const CREATE_LEADS_FAILED = "CREATE_LEADS_FAILED";

export const GET_LEADS_LOADING = "GET_LEADS_LOADING";
export const GET_LEADS_SUCCESS = "GET_LEADS_SUCCESS";
export const GET_LEADS_FAILED = "GET_LEADS_FAILED";