export const GET_ALL_LEADS_LOADING = "GET_ALL_LEADS_LOADING";
export const GET_ALL_LEADS_SUCCESS = "GET_ALL_LEADS_SUCCESS";
export const GET_ALL_LEADS_FAILED = "GET_ALL_LEADS_FAILED";

export const DELETE_LEADS_BY_ID_LOADING = "DELETE_LEADS_BY_ID_LOADING";
export const DELETE_LEADS_BY_ID_SUCCESS = "DELETE_LEADS_BY_ID_SUCCESS";
export const DELETE_LEADS_BY_ID_ERROR = "DELETE_LEADS_BY_ID_ERROR";

export const UPDATE_LEADS_BY_ID_LOADING = "UPDATE_LEADS_BY_ID_LOADING";
export const UPDATE_LEADS_BY_ID_SUCCESS = "UPDATE_LEADS_BY_ID_SUCCESS";
export const UPDATE_LEADS_BY_ID_ERROR = "UPDATE_LEADS_BY_ID_ERROR";