export const GET_PROJECTS_LOADING = "GET_PROJECTS_LOADING";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED";

export const DELETE_PROJECTS_USER_LOADING = "DELETE_PROJECTS_USER_LOADING";
export const DELETE_PROJECTS_USER_SUCCESS = "DELETE_PROJECTS_USER_SUCCESS";
export const DELETE_PROJECTS_USER_FAILED = "DELETE_PROJECTS_USER_FAILED";

export const DELETE_PROJECTS_LOADING = "DELETE_PROJECTS_LOADING";
export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECTS_SUCCESS";
export const DELETE_PROJECTS_FAILED = "DELETE_PROJECTS_FAILED";

export const UPDATE_PROJECTS_LOADING = "UPDATE_PROJECTS_LOADING";
export const UPDATE_PROJECTS_SUCCESS = "UPDATE_PROJECTS_SUCCESS";
export const UPDATE_PROJECTS_FAILED = "UPDATE_PROJECTS_FAILED";

export const DELETE_PROJECTS_TAG_LOADING = "DELETE_PROJECTS_TAG_LOADING";
export const DELETE_PROJECTS_TAG_SUCCESS = "DELETE_PROJECTS_TAG_SUCCESS";
export const DELETE_PROJECTS_TAG_FAILED = "DELETE_PROJECTS_TAG_FAILED";