export const CREATE_INVOICE_LOADING = "CREATE_INVOICE_LOADING";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_FAILED = "CREATE_INVOICE_FAILED";

export const GETALL_INVOICE_LOADING = "GETALL_INVOICE_LOADING";
export const GETALL_INVOICE_SUCCESS = "GETALL_INVOICE_SUCCESS";
export const GETALL_INVOICE_FAILED = "GETALL_INVOICE_FAILED";